
name: Pull Request

on:
  pull_request:
    branches:
      - develop
      - main
    types: [opened, synchronize]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - name: Install Dependencies
        run: yarn install --pure-lockfile

  lint:
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - run: yarn lint

  pr-success-slack:
    needs: lint
    if: ${{ success() }}
    name: Success notification
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: come25136/workflow-notification-for-slack@main
        with:
          include_jobs: true
          repo_token: ${{secrets.RRIOS_DEV_GITHUB_REPOSITORY }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          name: ${{github.repository}} - PR ready
          icon_emoji: ':art:'

  pr-failed-slack:
    needs: lint
    if: ${{ failure() }}
    name: Failed notification
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: come25136/workflow-notification-for-slack@main
        with:
          include_jobs: true
          repo_token: ${{secrets.RRIOS_DEV_GITHUB_REPOSITORY }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          name: ${{github.repository}} - PR failed
          icon_emoji: ':art:'
